#!/bin/bash
sed "s|sedchanges|$PWD|g" "$PWD/cppfile.tmp" > bin/cppfile

which bash > /dev/null 2>&1
if [ $? -eq 0 ]
then
	grep autoCreateFileCpp ~/.bashrc  > /dev/null 2>&1
	if [ $? -ne 0 ]
	then
		echo "export PATH=\"$PWD/autoCreateFileCpp/bin:$PATH\"" >> ~/.bashrc
		source ~/.bashrc
	fi
fi

which zsh > /dev/null 2>&1
if [ $? -eq 0 ]
then
	grep autoCreateFileCpp ~/.zshrc  > /dev/null 2>&1
	if [ $? -ne 0 ]
	then
		echo "export PATH=\"$PWD/autoCreateFileCpp/bin:$PATH\"" >> ~/.zshrc
		source ~/.zshrc
	fi
fi